version: '3.7'

volumes:
    logs:
        driver: local

services:
    database:
        container_name: database
        image: postgres
        restart: always
        env_file:
            - .env
        expose:
            - "${POSTGRES_PORT}"
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data:z

    php:
        container_name: php
        image: php:8-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        depends_on:
            - database
            - amqp

    ampq:
        container_name: amqp
        image: rabbitmq:3.8-management
        restart: always
        ports:
            - "1${AMQP_PORT}:15672"
            - "${AMQP_PORT}:5672"

    go:
        build:
            context: .
            dockerfile: ./go/Dockerfile
        env_file: .env
        depends_on:
            - database
            - amqp
        networks:
            - default
